=== SnowOnion/automataprojectexam/Home_27_NDFAConverter/autoDS.dtd
<?xml version="1.0" encoding="utf-8"?>
	<!ELEMENT Automatas (DFA | NFA | PDA)*>
	<!ELEMENT DFA (States, InputSymbols, TranFuncs, StartQ, FinalStates)>
	<!ELEMENT NFA (States, InputSymbols, TranFuncs, StartQ, FinalStates)>
	<!ELEMENT PDA (States, InputSymbols, PStackAlphabets, PTranFuncs, StartQ, PStartS, PFinalStates)>
	<!ELEMENT States (state+)>
	<!ELEMENT InputSymbols (symbol*)>
	<!ELEMENT TranFuncs (Tranfunc*)>
	<!ELEMENT PTranFuncs (PTranfunc*)>
	<!ELEMENT StartQ (state)>
	<!ELEMENT FinalStates (state+)>
	<!ELEMENT PFinalStates (state*)>
	<!ELEMENT PStackAlphabets (PStackAlphabet*)>
	<!ELEMENT PStartS (PStackAlphabet)>
	<!ELEMENT Tranfunc (state,symbol,state)>
	<!ELEMENT PTranfunc (state,symbol,state,PStackAlphabet,PushString)>	
	<!ELEMENT PushString (PStackAlphabet*)>
	<!ELEMENT state (#PCDATA)>
	<!ELEMENT symbol (#PCDATA)>
	<!ELEMENT PStackAlphabet (#PCDATA)>
	<!ATTLIST DFA name CDATA "">
	<!ATTLIST NFA name CDATA "">
	<!ATTLIST PDA name CDATA "">

=== SnowOnion/automataprojectexam/trunk/Home_27_NDFAConverter/Example.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Automatas SYSTEM "autoDS.dtd" >
<Automatas><NFA name="Example">
		<States>
			<state>p</state>
			<state>q</state>
			<state>r</state>
		</States>
		<InputSymbols>
			<symbol>a</symbol>
			<symbol>b</symbol>
			<symbol>c</symbol>
		</InputSymbols>
		<TranFuncs>
			<Tranfunc>
				<state>p</state>
				<symbol>^</symbol>
				<state>q</state>
			</Tranfunc>
			<Tranfunc>
				<state>p</state>
				<symbol>^</symbol>
				<state>r</state>
			</Tranfunc>
			<Tranfunc>
				<state>p</state>
				<symbol>b</symbol>
				<state>q</state>
			</Tranfunc>
			<Tranfunc>
				<state>p</state>
				<symbol>c</symbol>
				<state>r</state>
			</Tranfunc>
			<Tranfunc>
				<state>q</state>
				<symbol>a</symbol>
				<state>p</state>
			</Tranfunc>
			<Tranfunc>
				<state>q</state>
				<symbol>b</symbol>
				<state>r</state>
			</Tranfunc>
			<Tranfunc>
				<state>q</state>
				<symbol>c</symbol>
				<state>p</state>
			</Tranfunc>
			<Tranfunc>
				<state>q</state>
				<symbol>c</symbol>
				<state>q</state>
			</Tranfunc></TranFuncs>
		<StartQ>
			<state>p</state>
		</StartQ>
		<FinalStates>
			<state>r</state>
		</FinalStates>
	</NFA>
</Automatas>

=== SnowOnion/automataprojectexam/Home_27_NDFAConverter/InFinite.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Automatas SYSTEM "autoDS.dtd" >
<Automatas><DFA>
		<States>
			<state>p</state>
		</States>
		<InputSymbols>
			<symbol>a</symbol>
		</InputSymbols>
		<TranFuncs>
			<Tranfunc>
				<state>p</state>
				<symbol>a</symbol>
				<state>p</state>
			</Tranfunc></TranFuncs>
		<StartQ>
			<state>p</state>
		</StartQ>
		<FinalStates>
			<state>p</state>
		</FinalStates>
	</DFA>
</Automatas>

=== SnowOnion/automataprojectexam/Home_27_NDFAConverter/Finite.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Automatas SYSTEM "autoDS.dtd" >
<Automatas><DFA>
		<States>
			<state>p</state>
			<state>q</state>
		</States>
		<InputSymbols>
			<symbol>a</symbol>
		</InputSymbols>
		<TranFuncs>
			<Tranfunc>
				<state>p</state>
				<symbol>a</symbol>
				<state>q</state>
			</Tranfunc></TranFuncs>
		<StartQ>
			<state>p</state>
		</StartQ>
		<FinalStates>
			<state>p</state>
		</FinalStates>
	</DFA>
</Automatas>

=== SnowOnion/automataprojectexam/Home_27_NDFAConverter/NFA1.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?><!DOCTYPE Automatas SYSTEM "autoDS.dtd"><Automatas><NFA name=""><States><state>q6</state><state>q5</state><state>q7</state><state>q2</state><state>q1</state><state>q4</state><state>q3</state></States><InputSymbols><symbol>b</symbol><symbol>a</symbol></InputSymbols><TranFuncs><Tranfunc><state>q1</state><symbol>^</symbol><state>q2</state></Tranfunc><Tranfunc><state>q1</state><symbol>^</symbol><state>q4</state></Tranfunc><Tranfunc><state>q2</state><symbol>^</symbol><state>q3</state></Tranfunc><Tranfunc><state>q3</state><symbol>^</symbol><state>q6</state></Tranfunc><Tranfunc><state>q5</state><symbol>^</symbol><state>q7</state></Tranfunc><Tranfunc><state>q6</state><symbol>^</symbol><state>q1</state></Tranfunc><Tranfunc><state>q4</state><symbol>a</symbol><state>q5</state></Tranfunc><Tranfunc><state>q5</state><symbol>b</symbol><state>q6</state></Tranfunc></TranFuncs><StartQ><state>q1</state></StartQ><FinalStates><state>q7</state><state>q6</state></FinalStates></NFA></Automatas>

=== SnowOnion/automataprojectexam/trunk/Home_27_NDFAConverter/Example2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Automatas SYSTEM "autoDS.dtd" >
<Automatas><NFA>
		<States>
			<state>p</state>
			<state>q</state>
			<state>r</state>
			<state>s</state>
		</States>
		<InputSymbols>
			<symbol>0</symbol>
			<symbol>1</symbol></InputSymbols>
		<TranFuncs>
			<Tranfunc>
				<state>p</state>
				<symbol>1</symbol>
				<state>q</state>
			</Tranfunc>
			<Tranfunc>
				<state>p</state>
				<symbol>0</symbol>
				<state>q</state>
			</Tranfunc>
			<Tranfunc>
				<state>p</state>
				<symbol>0</symbol>
				<state>s</state>
			</Tranfunc>
			<Tranfunc>
				<state>q</state>
				<symbol>0</symbol>
				<state>r</state>
			</Tranfunc>
			<Tranfunc>
				<state>q</state>
				<symbol>1</symbol>
				<state>r</state>
			</Tranfunc>
			<Tranfunc>
				<state>q</state>
				<symbol>1</symbol>
				<state>q</state>
			</Tranfunc>
			<Tranfunc>
				<state>r</state>
				<symbol>0</symbol>
				<state>s</state>
			</Tranfunc>
			<Tranfunc>
				<state>r</state>
				<symbol>1</symbol>
				<state>p</state>
			</Tranfunc>
			<Tranfunc>
				<state>s</state>
				<symbol>1</symbol>
				<state>p</state>
			</Tranfunc></TranFuncs>
		<StartQ>
			<state>p</state>
		</StartQ>
		<FinalStates>
			<state>q</state>
			<state>s</state>
		</FinalStates>
	</NFA>
</Automatas>
