=== SnowOnion/automataprojectexam/trunk/21Conversion/AutomatonConversion/src/data/FA.dtd
<!--
 * Create by: huangcd
 * Date: 2009-12-10
 * Time: 10:02:42
-->
<!ELEMENT FiniteAutomaton (States,InputSymbols,Transitions)>
    <!-- Type information is required -->
    <!ATTLIST FiniteAutomaton type (DFA | NFA) #REQUIRED>
    <!-- name is nullable -->
    <!ATTLIST FiniteAutomaton name CDATA "unnamed">

    <!ELEMENT States (State+)>
        <!ELEMENT State (StateTypes)>
            <!-- stateID must be unique, and required -->
            <!ATTLIST State stateID ID #REQUIRED>
            <!ELEMENT StateTypes (StateType+)>
                <!ELEMENT StateType EMPTY>
                    <!ATTLIST StateType type (INITIAL | FINAL | COMMON) #REQUIRED>
                
    <!ELEMENT InputSymbols (InputSymbol+)>
        <!ELEMENT InputSymbol EMPTY>
            <!-- symbol must be unique, and required -->
            <!ATTLIST InputSymbol symbol ID #REQUIRED>

    <!ELEMENT Transitions (Transition*)>
        <!ELEMENT Transition (FromState,Conditions?,ToStates)>
        <!ELEMENT FromState EMPTY>             
            <!-- stateID must be appeared before -->
            <!ATTLIST FromState stateID IDREF #REQUIRED>
        <!ELEMENT Conditions (Condition)>
            <!ELEMENT Condition EMPTY>
            <!-- symbol must be appeared before -->
            <!ATTLIST Condition symbol IDREF #REQUIRED>
            <!-- stateID must be appeared before -->
        <!ELEMENT ToStates (ToState+)>
            <!ELEMENT ToState EMPTY>
                <!ATTLIST ToState stateID IDREF #REQUIRED>

=== SnowOnion/automataprojectexam/trunk/21Conversion/data/aComplexDFA.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE FiniteAutomaton SYSTEM "FA.dtd">
<FiniteAutomaton type="DFA" name="Graph_2_22">
    <States>
        <State stateID="Q01">
            <StateTypes>
                <StateType type="INITIAL"/>
            </StateTypes>
        </State>
        <State stateID="Q1">
            <StateTypes>
                <StateType type="COMMON"/>
            </StateTypes>
        </State>
        <State stateID="Q14">
            <StateTypes>
                <StateType type="COMMON"/>
            </StateTypes>
        </State>
        <State stateID="Q2">
            <StateTypes>
                <StateType type="COMMON"/>
            </StateTypes>
        </State>
        <State stateID="Q235">
            <StateTypes>
                <StateType type="FINAL"/>
            </StateTypes>
        </State>
        <State stateID="Q35">
            <StateTypes>
                <StateType type="FINAL"/>
            </StateTypes>
        </State>
    </States>
    <InputSymbols>
        <InputSymbol symbol="Dot"/>
        <InputSymbol symbol="Pos"/>
        <InputSymbol symbol="Neg"/>
        <InputSymbol symbol="s0"/>
        <InputSymbol symbol="s1"/>
        <InputSymbol symbol="s2"/>
        <InputSymbol symbol="s3"/>
        <InputSymbol symbol="s4"/>
        <InputSymbol symbol="s5"/>
        <InputSymbol symbol="s6"/>
        <InputSymbol symbol="s7"/>
        <InputSymbol symbol="s8"/>
        <InputSymbol symbol="s9"/>
    </InputSymbols>
    <Transitions>
        <Transition>
            <FromState stateID="Q01"/>
            <Conditions>
                <Condition symbol="Pos"/>
                <Condition symbol="Neg"/>
            </Conditions>
            <ToStates>
                <ToState stateID="Q1"/>
            </ToStates>
        </Transition>
        <Transition>
            <FromState stateID="Q01"/>
            <Conditions>
                <Condition symbol="s0"/>
                <Condition symbol="s1"/>
                <Condition symbol="s2"/>
                <Condition symbol="s3"/>
                <Condition symbol="s4"/>
                <Condition symbol="s5"/>
                <Condition symbol="s6"/>
                <Condition symbol="s7"/>
                <Condition symbol="s8"/>
                <Condition symbol="s9"/>
            </Conditions>
            <ToStates>
                <ToState stateID="Q14"/>
            </ToStates>
        </Transition>
        <Transition>
            <FromState stateID="Q1"/>
            <Conditions>
                <Condition symbol="s0"/>
                <Condition symbol="s1"/>
                <Condition symbol="s2"/>
                <Condition symbol="s3"/>
                <Condition symbol="s4"/>
                <Condition symbol="s5"/>
                <Condition symbol="s6"/>
                <Condition symbol="s7"/>
                <Condition symbol="s8"/>
                <Condition symbol="s9"/>
            </Conditions>
            <ToStates>
                <ToState stateID="Q14"/>
            </ToStates>
        </Transition>
        <Transition>
            <FromState stateID="Q14"/>
            <Conditions>
                <Condition symbol="s0"/>
                <Condition symbol="s1"/>
                <Condition symbol="s2"/>
                <Condition symbol="s3"/>
                <Condition symbol="s4"/>
                <Condition symbol="s5"/>
                <Condition symbol="s6"/>
                <Condition symbol="s7"/>
                <Condition symbol="s8"/>
                <Condition symbol="s9"/>
            </Conditions>
            <ToStates>
                <ToState stateID="Q14"/>
            </ToStates>
        </Transition>
        <Transition>
            <FromState stateID="Q01"/>
            <Conditions>
                <Condition symbol="Dot"/>
            </Conditions>
            <ToStates>
                <ToState stateID="Q2"/>
            </ToStates>
        </Transition>
        <Transition>
            <FromState stateID="Q1"/>
            <Conditions>
                <Condition symbol="Dot"/>
            </Conditions>
            <ToStates>
                <ToState stateID="Q2"/>
            </ToStates>
        </Transition>
        <Transition>
            <FromState stateID="Q14"/>
            <Conditions>
                <Condition symbol="Dot"/>
            </Conditions>
            <ToStates>
                <ToState stateID="Q235"/>
            </ToStates>
        </Transition>
        <Transition>
            <FromState stateID="Q2"/>
            <Conditions>
                <Condition symbol="s0"/>
                <Condition symbol="s1"/>
                <Condition symbol="s2"/>
                <Condition symbol="s3"/>
                <Condition symbol="s4"/>
                <Condition symbol="s5"/>
                <Condition symbol="s6"/>
                <Condition symbol="s7"/>
                <Condition symbol="s8"/>
                <Condition symbol="s9"/>
            </Conditions>
            <ToStates>
                <ToState stateID="Q35"/>
            </ToStates>
        </Transition>
        <Transition>
            <FromState stateID="Q35"/>
            <Conditions>
                <Condition symbol="s0"/>
                <Condition symbol="s1"/>
                <Condition symbol="s2"/>
                <Condition symbol="s3"/>
                <Condition symbol="s4"/>
                <Condition symbol="s5"/>
                <Condition symbol="s6"/>
                <Condition symbol="s7"/>
                <Condition symbol="s8"/>
                <Condition symbol="s9"/>
            </Conditions>
            <ToStates>
                <ToState stateID="Q35"/>
            </ToStates>
        </Transition>
        <Transition>
            <FromState stateID="Q235"/>
            <Conditions>
                <Condition symbol="s0"/>
                <Condition symbol="s1"/>
                <Condition symbol="s2"/>
                <Condition symbol="s3"/>
                <Condition symbol="s4"/>
                <Condition symbol="s5"/>
                <Condition symbol="s6"/>
                <Condition symbol="s7"/>
                <Condition symbol="s8"/>
                <Condition symbol="s9"/>
            </Conditions>
            <ToStates>
                <ToState stateID="Q35"/>
            </ToStates>
        </Transition>
    </Transitions>
</FiniteAutomaton>

=== SnowOnion/automataprojectexam/21Conversion/data/NFA2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE FiniteAutomaton SYSTEM "FA.dtd">
<FiniteAutomaton type="NFA" name="graph 2.18">
    <States>
        <State stateID="q0">
            <StateTypes>
                <StateType type="INITIAL"/>
            </StateTypes>
        </State>
        <State stateID="q1">
            <StateTypes>
                <StateType type="COMMON"/>
            </StateTypes>
        </State>
        <State stateID="q2">
            <StateTypes>
                <StateType type="COMMON"/>
            </StateTypes>
        </State>
        <State stateID="q3">
            <StateTypes>
                <StateType type="COMMON"/>
            </StateTypes>
        </State>
        <State stateID="q4">
            <StateTypes>
                <StateType type="COMMON"/>
            </StateTypes>
        </State>
        <State stateID="q5">
            <StateTypes>
                <StateType type="FINAL"/>
            </StateTypes>
        </State>
    </States>
    <InputSymbols>
        <InputSymbol symbol="s0"/>
        <InputSymbol symbol="s1"/>
        <InputSymbol symbol="s2"/>
        <InputSymbol symbol="s3"/>
        <InputSymbol symbol="s4"/>
        <InputSymbol symbol="s5"/>
        <InputSymbol symbol="s6"/>
        <InputSymbol symbol="s7"/>
        <InputSymbol symbol="s8"/>
        <InputSymbol symbol="s9"/>
        <InputSymbol symbol="dot"/>
        <InputSymbol symbol="pos"/>
        <InputSymbol symbol="neg"/>
    </InputSymbols>
    <Transitions>
        <Transition>
            <FromState stateID="q0"/>
            <Conditions>
                <Condition symbol="pos"/>
                <Condition symbol="neg"/>
            </Conditions>
            <ToStates>
                <ToState stateID="q1"/>
            </ToStates>
        </Transition>
        <Transition>
            <FromState stateID="q0"/>
            <ToStates>
                <ToState stateID="q1"/>
            </ToStates>
        </Transition>         
        <Transition>
            <FromState stateID="q1"/>
            <Conditions>
                <Condition symbol="s0"/>
                <Condition symbol="s1"/>
                <Condition symbol="s2"/>
                <Condition symbol="s3"/>
                <Condition symbol="s4"/>
                <Condition symbol="s5"/>
                <Condition symbol="s6"/>
                <Condition symbol="s7"/>
                <Condition symbol="s8"/>
                <Condition symbol="s9"/>
            </Conditions>
            <ToStates>
                <ToState stateID="q4"/>
                <ToState stateID="q1"/>
            </ToStates>
        </Transition>
        <Transition>
            <FromState stateID="q1"/>
            <Conditions>
                <Condition symbol="dot"/>
            </Conditions>
            <ToStates>
                <ToState stateID="q2"/>
            </ToStates>
        </Transition>
        <Transition>
            <FromState stateID="q4"/>
            <Conditions>
                <Condition symbol="dot"/>
            </Conditions>
            <ToStates>
                <ToState stateID="q3"/>
            </ToStates>
        </Transition>
        <Transition>
            <FromState stateID="q2"/>
            <Conditions>
                <Condition symbol="s0"/>
                <Condition symbol="s1"/>
                <Condition symbol="s2"/>
                <Condition symbol="s3"/>
                <Condition symbol="s4"/>
                <Condition symbol="s5"/>
                <Condition symbol="s6"/>
                <Condition symbol="s7"/>
                <Condition symbol="s8"/>
                <Condition symbol="s9"/>
            </Conditions>
            <ToStates>
                <ToState stateID="q3"/>
            </ToStates>
        </Transition>
        <Transition>
            <FromState stateID="q3"/>
            <Conditions>
                <Condition symbol="s0"/>
                <Condition symbol="s1"/>
                <Condition symbol="s2"/>
                <Condition symbol="s3"/>
                <Condition symbol="s4"/>
                <Condition symbol="s5"/>
                <Condition symbol="s6"/>
                <Condition symbol="s7"/>
                <Condition symbol="s8"/>
                <Condition symbol="s9"/>
            </Conditions>
            <ToStates>
                <ToState stateID="q3"/>
            </ToStates>
        </Transition>
        <Transition>
            <FromState stateID="q3"/>
            <ToStates>
                <ToState stateID="q5"/>
            </ToStates>
        </Transition>
    </Transitions>
</FiniteAutomaton>

=== SnowOnion/automataprojectexam/trunk/21Conversion/AutomatonConversion/src/data/aComplexNFA.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE FiniteAutomaton SYSTEM "FA.dtd">
<FiniteAutomaton type="NFA" name="exercise 2.5.2" >
    <States>
        <State stateID="p">
            <StateTypes>
                <StateType type="INITIAL"/>
                <StateType type="COMMON"/>
            </StateTypes>
        </State>
        <State stateID="q">
            <StateTypes>
                <StateType type="COMMON"/>
            </StateTypes>
        </State>
        <State stateID="r">
            <StateTypes>
                <StateType type="FINAL"/>
                <StateType type="COMMON"/>
            </StateTypes>
        </State>
    </States>
    <InputSymbols>
        <InputSymbol symbol="a"/>
        <InputSymbol symbol="b"/>
        <InputSymbol symbol="c"/>
    </InputSymbols>
    <Transitions>
        <Transition>
            <FromState stateID="p"/>
            <ToStates>
                <ToState stateID="q"/>
                <ToState stateID="r"/>
            </ToStates>
        </Transition>
        <Transition>
            <FromState stateID="p"/>
            <Conditions>
                <Condition symbol="b"/>
            </Conditions>
            <ToStates>
                <ToState stateID="q"/>
            </ToStates>
        </Transition>
        <Transition>
            <FromState stateID="p"/>
            <Conditions>
                <Condition symbol="c"/>
            </Conditions>
            <ToStates>
                <ToState stateID="r"/>
            </ToStates>
        </Transition>
        <Transition>
            <FromState stateID="q"/>
            <Conditions>
                <Condition symbol="a"/>
            </Conditions>
            <ToStates>
                <ToState stateID="p"/>
            </ToStates>
        </Transition>
        <Transition>
            <FromState stateID="q"/>
            <Conditions>
                <Condition symbol="b"/>
            </Conditions>
            <ToStates>
                <ToState stateID="r"/>
            </ToStates>
        </Transition>
        <Transition>
            <FromState stateID="q"/>
            <Conditions>
                <Condition symbol="c"/>
            </Conditions>
            <ToStates>
                <ToState stateID="p"/>
                <ToState stateID="q"/>
            </ToStates>
        </Transition>
    </Transitions>
</FiniteAutomaton>

=== SnowOnion/automataprojectexam/21Conversion/AutomatonConversion/src/data/bak/nfa.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE FiniteAutomaton SYSTEM "FA.dtd">

<FiniteAutomaton type="NFA">
    <States>
        <State stateID="P1">
            <StateTypes>
                <StateType type="INITIAL"/>
                <StateType type="FINAL"/>
            </StateTypes>
        </State>
        <State stateID="P2">
            <StateTypes>
                <StateType type="COMMON"/>
            </StateTypes>
        </State>
    </States>
    <InputSymbols>
        <InputSymbol symbol="a"/>
        <InputSymbol symbol="b"/>
    </InputSymbols>
    <Transitions>
        <Transition>
            <FromState stateID="P1"/>
            <Conditions>
                <Condition symbol="a"/>
            </Conditions>
            <ToStates>
                <ToState stateID="P1"/>
            </ToStates>
        </Transition>
        <Transition>
            <FromState stateID="P1"/>
            <Conditions>
                <Condition symbol="a"/>
            </Conditions>
            <ToStates>
                <ToState stateID="P2"/>
            </ToStates>
        </Transition>
    </Transitions>
</FiniteAutomaton>

=== SnowOnion/automataprojectexam/trunk/21Conversion/data/NFA3.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE FiniteAutomaton SYSTEM "FA.dtd">
<FiniteAutomaton type="NFA" name="graph 2_19">
    <States>
        <State stateID="q0">
            <StateTypes>
                <StateType type="COMMON"/>
            </StateTypes>
        </State>
        <State stateID="q1">
            <StateTypes>
                <StateType type="COMMON"/>
            </StateTypes>
        </State>
        <State stateID="q2">
            <StateTypes>
                <StateType type="COMMON"/>
            </StateTypes>
        </State>
        <State stateID="q3">
            <StateTypes>
                <StateType type="COMMON"/>
            </StateTypes>
        </State>
        <State stateID="q4">
            <StateTypes>
                <StateType type="FINAL"/>
            </StateTypes>
        </State>
        <State stateID="q5">
            <StateTypes>
                <StateType type="COMMON"/>
            </StateTypes>
        </State>
        <State stateID="q6">
            <StateTypes>
                <StateType type="COMMON"/>
            </StateTypes>
        </State>
        <State stateID="q7">
            <StateTypes>
                <StateType type="COMMON"/>
            </StateTypes>
        </State>
        <State stateID="q8">
            <StateTypes>
                <StateType type="FINAL"/>
            </StateTypes>
        </State>
        <State stateID="q9">
            <StateTypes>
                <StateType type="INITIAL"/>
            </StateTypes>
        </State>
    </States>
    <InputSymbols>
        <InputSymbol symbol="w"/>
        <InputSymbol symbol="e"/>
        <InputSymbol symbol="b"/>
        <InputSymbol symbol="a"/>
        <InputSymbol symbol="y"/>
    </InputSymbols>
    <Transitions>
        <Transition>
            <FromState stateID="q9"/>
            <Conditions>
                <Condition symbol="w"/>
                <Condition symbol="e"/>
                <Condition symbol="b"/>
                <Condition symbol="a"/>
                <Condition symbol="y"/>
            </Conditions>
            <ToStates>
                <ToState stateID="q9"/>
            </ToStates>
        </Transition>
        <Transition>
            <FromState stateID="q9"/>
            <ToStates>
                <ToState stateID="q0"/>
                <ToState stateID="q1"/>
            </ToStates>
        </Transition>
        <Transition>
            <FromState stateID="q1"/>
            <Conditions>
                <Condition symbol="w"/>
            </Conditions>
            <ToStates>
                <ToState stateID="q2"/>
            </ToStates>
        </Transition>
        <Transition>
            <FromState stateID="q2"/>
            <Conditions>
                <Condition symbol="e"/>
            </Conditions>
            <ToStates>
                <ToState stateID="q3"/>
            </ToStates>
        </Transition>
        <Transition>
            <FromState stateID="q3"/>
            <Conditions>
                <Condition symbol="b"/>
            </Conditions>
            <ToStates>
                <ToState stateID="q4"/>
            </ToStates>
        </Transition>
        <Transition>
            <FromState stateID="q0"/>
            <Conditions>
                <Condition symbol="e"/>
            </Conditions>
            <ToStates>
                <ToState stateID="q5"/>
            </ToStates>
        </Transition>
        <Transition>
            <FromState stateID="q5"/>
            <Conditions>
                <Condition symbol="b"/>
            </Conditions>
            <ToStates>
                <ToState stateID="q6"/>
            </ToStates>
        </Transition>
        <Transition>
            <FromState stateID="q6"/>
            <Conditions>
                <Condition symbol="a"/>
            </Conditions>
            <ToStates>
                <ToState stateID="q7"/>
            </ToStates>
        </Transition>
        <Transition>
            <FromState stateID="q7"/>
            <Conditions>
                <Condition symbol="y"/>
            </Conditions>
            <ToStates>
                <ToState stateID="q8"/>
            </ToStates>
        </Transition>
    </Transitions>
</FiniteAutomaton>
